### ISSUE TITLE
Add support for .srt subtitle captions for courses

### ISSUE THREAD

**Issue by Monkeyboy200** [Ilyas-Codes/eCourse#8]
I am not sure if this counts as an "issue" but I would love to see native support for .srt files in the caption section for each lesson!

Thank you!

**Comment by Ilyas-Codes** [comment]
I'm not familiar with .srt files, which is why I omitted them from the captions. but PocketBase does support .srt files. you can add it yourself. go to the Admin UI -> lessons collection -> click the gear icon -> click the gear icon for the captions field -> Under "Allowed mime types," you can add `.srt` to enable support for .srt files.
